package com.ffpalu.concessionaria.batch;

import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.jspecify.annotations.Nullable;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.StepContribution;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.infrastructure.repeat.RepeatStatus;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

import java.io.File;

@Component
@RequiredArgsConstructor
public class SendEmailTasklet implements Tasklet {

	private final JavaMailSender mailSender;

	@Override
	public @Nullable RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {

		String csvPath = chunkContext
						.getStepContext()
						.getStepExecution()
						.getJobExecution()
						.getExecutionContext()
						.getString("csvFilePath");

		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		helper.setTo("admin@concessionaria.com");
		helper.setFrom("noreply@concessionaria.com");
		helper.setSubject("Monthly Report Sales");
		helper.setText("AUTOGENERATED MAIL(do not reply) - Attached is the report from the previous month");

		FileSystemResource file = new FileSystemResource(new File(csvPath));
		helper.addAttachment(file.getFilename(), file);

		mailSender.send(message);

		return RepeatStatus.FINISHED;

	}

}
